SELECT BranchName, Title, No_Of_Copies
FROM LIBRARY_BRANCH 
INNER JOIN BOOK_COPIES
ON LIBRARY_BRANCH.Branchid = BOOK_COPIES.Branchid
INNER JOIN BOOK
ON BOOK_COPIES.Bookid = BOOK.Bookid
WHERE BranchName = 'Sharpstown' AND Title = 'The Lost Tribe';

SELECT BranchName, Title, No_Of_Copies
FROM LIBRARY_BRANCH 
INNER JOIN BOOK_COPIES
ON LIBRARY_BRANCH.Branchid = BOOK_COPIES.Branchid
INNER JOIN BOOK
ON BOOK_COPIES.Bookid = BOOK.Bookid
WHERE Title = 'The Lost Tribe';

SELECT Name
FROM BORROWER
LEFT OUTER JOIN BOOK_LOANS
ON BORROWER.CardNo = BOOK_LOANS.CardNo
WHERE DateOut IS NULL;

SELECT Title, Name, BORROWER.[Address]
FROM LIBRARY_BRANCH 
INNER JOIN BOOK_LOANS
ON LIBRARY_BRANCH.Branchid = BOOK_LOANS.Branchid
INNER JOIN BORROWER
ON BOOK_LOANS.CardNo = BORROWER.CardNo
INNER JOIN BOOK
ON BOOK_LOANS.Bookid = BOOK.Bookid
WHERE BranchName = 'Sharpstown' AND DueDate = '2016-11-21';

SELECT BranchName, COUNT(BOOK_LOANS.Branchid) AS Books_CheckedOut
FROM LIBRARY_BRANCH 
INNER JOIN BOOK_LOANS
ON LIBRARY_BRANCH.Branchid = BOOK_LOANS.Branchid
GROUP BY BranchName;

SELECT Name, [Address], COUNT(BOOK_LOANS.CardNo) AS Books_CheckedOut
FROM BORROWER
INNER JOIN BOOK_LOANS
ON BORROWER.CardNo = BOOK_LOANS.CardNo
GROUP BY Name, [Address]
HAVING COUNT(BOOK_LOANS.CardNo) > 5;

SELECT Title, No_Of_Copies
FROM LIBRARY_BRANCH 
INNER JOIN BOOK_COPIES
ON LIBRARY_BRANCH.Branchid = BOOK_COPIES.Branchid
INNER JOIN BOOK
ON BOOK_COPIES.Bookid = BOOK.Bookid
INNER JOIN BOOK_AUTHORS
ON BOOK.Bookid = BOOK_AUTHORS.Bookid
WHERE BranchName = 'Central' AND AuthorName = 'Stephen King';

